spring:
  profiles:
    active: dev

---
server:
  port: 8001
spring:
    profiles: dev #开发环境
    application:
       name: springcloud-config-dept-client
eureka:
   client:
     service-url:
       defaultZone: http://eureka7001.com:7001/eureka/
   instance:
       instance-id: dept-8001.com
       prefer-ip-address: true

---
server:
  port: 8001
spring:
    profiles: test #开发环境
    application:
       name: springcloud-config-dept-client
eureka:
   client:
     service-url:
       defaultZone: http://eureka7001.com:7001/eureka/

   instance:
     instance-id: dept-8001.com
     prefer-ip-address: true