spring:
  profiles:
    active:
     -dev
---
server:
  port: 8201
spring:
    profiles: dev #开发环境
    application:
       name:springcloud-config-dev
eureka:
   client:
     service-url:
       defaultZone=http://eureka-dev.com:7001/eureka/
---
spring:
    profiles: test#开发环境
    application:
       name:springcloud-config-test
eureka:
   client:
     service-url:
       defaultZone=http://eureka-test.com:7001/eureka/
